### PR TITLE
Fixed HttpSender

### LINKED ISSUE #80: Required field Process is not set
Hello, 

after trying the latest version (0.1.0), I get an error from Jaeger server: 
`Unable to process request body: Required field Process is not set\n`. 
Could you help me? 

My configuration: 
```csharp
            var senderConfiguration = new Configuration.SenderConfiguration(loggerFactory)
                .WithEndpoint($"http://{jaegerConfig.ServerIp}:{jaegerConfig.ServerPort}/api/traces");

            var reporterConfiguration = new Configuration.ReporterConfiguration(loggerFactory)
                .WithSender(senderConfiguration);

            var samplerConfiguration = new Configuration.SamplerConfiguration(loggerFactory)
                .WithType("const");

            Tracer = new Configuration(serviceInfo.ServiceId, loggerFactory)
                .WithReporter(reporterConfiguration)
                .WithSampler(samplerConfiguration)
                .GetTracer();
```

Usage:
```csharp
           var builder = _tracer.Tracer
                .BuildSpan("HomeControler request")
                .WithTag("Server", Tags.SpanKindServer)
                .WithTag("Client", Tags.SpanKindClient)
                .WithTag(Tags.DbInstance.Key, "")
                .WithTag(Tags.DbType.Key, "sql");

            using (var scope = builder.StartActive(true))
            {
                var span = scope.Span;

                ViewBag.Title = "My Sample";
                span.SetOperationName("Home page");
                span.SetTag("smth", "special value");

                using (var scope2 = _tracer.Tracer.BuildSpan("Home page 2").StartActive(true))
                {
                    var span2 = scope2.Span;
                    span2.Log("Before scope 2");

                    Task.Delay(2000).Wait();

                    span2.Log("After scope 2");
                }

                span.SetTag("smth2", "special value 2");
            }
```

BTW, a lot of errors were swallowed, so I had to debug it locally to figure out the real issue. 
For example: 
`RemoteReporter`, line 135 (`catch (SenderException ex)`) only report through `_metrics.ReporterFailure`, but not to `_logger`, so when I forgot `http://` in an url, it didn't do anything. 
`THttpClientTransport`, line 180 (`msg.EnsureSuccessStatusCode();`) it throws exception, but doesn't return message from server. 
If you help me with this issue, I can provide PR for logging correction.

### PR DESCRIPTION
**Pull request by Falco20019**
Fixes #80 

We got this error introduced by `v0.0.10`. I used the implementation from Java again which differed from our port.

### CODE REVIEW

File: src/Jaeger/Senders/HttpSender.cs [hunk 1]
```diff
@@ -45,15 +46,16 @@ private HttpSender(Builder builder)
...
+            _protocol = ProtocolFactory.GetProtocol(_transport);
         }
 
         protected override async Task SendAsync(ThriftProcess process, List<ThriftSpan> spans, CancellationToken cancellationToken)
         {
             try
             {
                 var batch = new ThriftBatch(process, spans);
-                await _agentClient.emitBatchAsync(batch, cancellationToken).ConfigureAwait(false);
+                await batch.WriteAsync(_protocol, cancellationToken);
```
Comment (cwe1ss) [inline src/Jaeger/Senders/HttpSender.cs]: .ConfigureAwait(false) is missing on both await calls.

File: src/Jaeger/Senders/HttpSender.cs [hunk 2]
```diff
@@ -45,15 +46,16 @@ private HttpSender(Builder builder)
...
-            _agentClient = new Agent.Client(ProtocolFactory.GetProtocol(_transport));
+            _protocol = ProtocolFactory.GetProtocol(_transport);
         }
 
         protected override async Task SendAsync(ThriftProcess process, List<ThriftSpan> spans, CancellationToken cancellationToken)
         {
             try
             {
                 var batch = new ThriftBatch(process, spans);
-                await _agentClient.emitBatchAsync(batch, cancellationToken).ConfigureAwait(false);
```
Comment (cwe1ss) [inline src/Jaeger/Senders/HttpSender.cs]: The existing UdpSender uses the same logic and that works fine, doesn't it? Is there different behavior in the UDP/HTTP endpoints of Jaeger?

File: src/Jaeger/Senders/HttpSender.cs (hunk 1 above)
Comment (Falco20019) [reply src/Jaeger/Senders/HttpSender.cs]: Will add them in a second. Thanks!

File: src/Jaeger/Senders/HttpSender.cs (hunk 2 above)
Comment (Falco20019) [reply src/Jaeger/Senders/HttpSender.cs]: There is a bit of asynchronity here. UDP uses `Agent.EmitBatch` with `TCompactProtocol` to send the `ThriftBatch` and HTTP is directly serializing `ThriftBatch` with `TBinaryProtocol` and sending it as byte array ([see Go endpoint](https://github.com/jaegertracing/jaeger/blob/8ed44f2dd9eeb71e323cd4ff93b1fee146fc6442/cmd/collector/app/http_handler.go#L70)). I made the same mistake when doing the `LetsTrace` HttpSender :)
